import express from 'express';
const router = express.Router();

// router.post(
//   '/tem/:name([a-zA-Z]+)',
//   validateRequest(
//     reactFolderCreatorZodValidation.reactFolderCreatorTemplateSchema
//   ),
//   reactFolderCreatorController.createReactTemplate
// );
// router.get(
//   '/:name([a-zA-Z]+)',
//   reactFolderCreatorService.createReactReduxFeatures
// );

export const createRectFolderRoute = router;
